// <auto-generated />
namespace BackEnd.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class Added_ukzed : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Added_ukzed));
        
        string IMigrationMetadata.Id
        {
            get { return "202110081122053_Added_ukzed"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
